### ISSUE TITLE
CWE support

### ISSUE THREAD

**Issue by oed** [digitalbazaar/minimal-cipher#20]
The readme says this library supports both JWE and CWE. Currently however there is only CWE support. How big of a lift would it be to add support for CWE?

**Comment by dlongley** [comment]
Since mention of CWE was added, we've discovered that CWE is not a straight translation of JWE, making it significantly more difficult to support and harder to get interop than previously expected. It is unlikely we'll be supporting it in this library any time soon, so I've removed mention of CWE for now. Closing this issue.
